### ISSUE TITLE
Multi task issue

### ISSUE THREAD

**Issue by brettcurtis** [osinfra-io/local-development-setup#95]
```[tasklist]
### Tasks
- [x] Install jq, kubectx, fzf, k9s
- [x] Run bundle update
- [ ] Don't rebuild images on release
- [x] Plugins need to be at the top of .zshrc
- [x] Install Open Policy Agent
- [x] Ubuntu doesn't need `gem install bundler`
- [x] Swith to ruby-lsp vscode extention and install required gems
- [x] Gentoo package.use updates
- [x] Run bundle clean --force
- [x] `gh extension install github/gh-copilot --force`
- [x] `gh extension install github/gh-projects`
- [x] `gh extension install actions/gh-actions-cache --force`
- [x] `gh extension install advanced-security/gh-sbom`
```

**Comment by brettcurtis** [comment]
Gentoo:

```none
cd bin
curl -L -o opa https://openpolicyagent.org/downloads/latest/opa_linux_amd64
chmod 755 opa
```

Ubuntu

```none
brew install opa
````
